### ISSUE TITLE
App crashes when importing video on windows

### ISSUE THREAD

**Issue by RyanYammine** [cyrilzakka/DaVid#4]
Using Python 3.9.7

When importing a video using the app I receive the following error
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "C:\Users\User\Desktop\DaVid\DaVid-main\DaVid.py", line 115, in load_video
    _, username = str(pathlib.Path.home()).rsplit('/', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by cyrilzakka** [comment]
Fixed.
